AtlasBlog/Controllers/BlogPostsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AtlasBlog.Data;
using AtlasBlog.Models;
using Microsoft.AspNetCore.Authorization;
using AtlasBlog.Services;
using AtlasBlog.Services.Interfaces;
using X.PagedList;

namespace AtlasBlog.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class BlogPostsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IImageService _imageService;
        private readonly SlugService _slugService;
        private readonly SearchService _searchService;

        public BlogPostsController(ApplicationDbContext context, SlugService slugService, IImageService imageService, 
                                                                SearchService searchService)
        {
            _context = context;
            _slugService = slugService;
            _imageService = imageService;
            _searchService = searchService;
        }

        [AllowAnonymous]
        // GET: BlogPosts
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.BlogPosts.Include(b => b.Blog);
            return View(await applicationDbContext.ToListAsync());
        }

        [AllowAnonymous]
        public async Task<IActionResult> SearchIndex(int? pageNum, string searchTerm)
        {
            pageNum ??= 1;
            var pageSize = 4;

            //  ---  SEARCH SERVICE WILL BE USED FOR THIS ----------------<
            var posts = _searchService.TermSearch(searchTerm);
            var pagedPosts = await posts.ToPagedListAsync(pageNum, pageSize);

            ViewData["SearchTerm"] = searchTerm;
            return View(pagedPosts);

        }

        [AllowAnonymous]
        [Authorize]
        // GET: BlogPosts/Details/5
        public async Task<IActionResult> Details(string slug)
        {
            if (string.IsNullOrEmpty(slug))
            {
                return NotFound();
            }

            var blogPost = await _context.BlogPosts
                .Include(b => b.Blog)
                .Include(c => c.Comments)
                .ThenInclude(c => c.Author)
                .FirstOrDefaultAsync(m => m.Slug== slug);

            if (blogPost == null)
            {
                return NotFound();
            }

            return View(blogPost);
        }

        //GET: BlogPosts/Create
        public IActionResult Create()
        {
            ViewData["BlogId"] = new SelectList(_context.Blogs, "Id", "BlogName");
            ViewData["TagIds"] = new MultiSelectList(_context.Tags, "Id", "Text");
            return View();
        }

        // POST: BlogPosts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,BlogId,Title,ResearchTopic,Abstract,BlogPostState,Body,Tags")] BlogPost blogPost, List<int> tagIds)
        {
            if (ModelState.IsValid)
            {
                var slug = _slugService.UrlFriendly(blogPost.Title, 100);

                // HAVE TO ENSURE THE SLUG IS UNIQUE BEFORE ALLOW TO BE STORED IN THE DB  ------------>
                // IF YES TO UNIQUE, CAN BE USED. OTHERWISE WE HAVE TO THROW A CUSTOM ERROR LETTING USER KNOW WHAT HAPPENED
                var isUnique = !_context.BlogPosts.Any(blogpost => blogPost.Slug == slug);

                if (isUnique)
                {
                    blogPost.Slug = slug;
                }
                else
                {
                    // THE SLUG CANNOT BE USED AND AN ERROR MUST BE SHOWN TO THE USER
                    ModelState.AddModelError("Title", "Incorrect TItle (duplicate SLUG)");
                    ModelState.AddModelError("", "Incorrect TItle (duplicate SLUG)");
                    ViewData["BlogId"] = new SelectList(_context.Blogs, "Id", "BlogName", blogPost.BlogId);
                    return View(blogPost);
                }

                // ------ CHECKING FOR ANY TAGS TO ADD ----------
                if (tagIds.Count > 0)
                {

                    var tags = _context.Tags;
                    foreach (var tagId in tagIds)
                    {
                        blogPost.Tags.Add(await tags.FindAsync(tagId));
                    };
                }


                blogPost.Created = DateTime.UtcNow;

                _context.Add(blogPost);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }

            ViewData["BlogId"] = new SelectList(_context.Blogs, "Id", "BlogId", blogPost.BlogId);
            ViewData["TagIds"] = new MultiSelectList(_context.Tags, "Id", "Text", tagIds);
            return View(blogPost);
        }

        
        [Authorize]
        // GET: BlogPosts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // var blogPost = await _context.BlogPosts.FindAsync(id);
            // var blogPost = await _context.BlogPosts.FindAsync(id);
            var blogPost = await _context.BlogPosts
                                                .Include("Tags")
                                                .FirstOrDefaultAsync(b => b.Id == id);

            var tagIds = await blogPost.Tags.Select(blogPost => blogPost.Id).ToListAsync();
            if (blogPost == null)

            {
                return NotFound();
            }

            ViewData["BlogId"] = new SelectList(_context.Blogs, "Id", "BlogName", blogPost.BlogId);
            ViewData["TagIds"] = new MultiSelectList(_context.Tags, "Id", "Text", tagIds);

            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BlogId,Title,ResearchTopic,Slug,IsDeleted,Abstract,BlogPostState,Body,Created")] BlogPost blogPost, List<int> tagIds)
        {
            if (id != blogPost.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                
                try
                {
                    // IF THE SLUG HAS CHANGED I NEED TO DO THIS CHECK ------------------->
                    var slug = _slugService.UrlFriendly(blogPost.Title, 100);

                    if (blogPost.Slug != slug)
                    {
                        // HAVE TO ENSURE THE SLUG IS UNIQUE BEFORE ALLOW TO BE STORED IN THE DB  ------------>
                        // IF YES TO UNIQUE, CAN BE USED. OTHERWISE WE HAVE TO THROW A CUSTOM ERROR LETTING USER KNOW WHAT HAPPENED
                        var isUnique = !_context.BlogPosts.Any(blogpost => blogPost.Slug == slug);

                        if (isUnique)
                        {
                            blogPost.Slug = slug;
                        }

                        else
                        {
                            // THE SLUG CANNOT BE USED AND AN ERROR MUST BE SHOWN TO THE USER
                            ModelState.AddModelError("Title", "Incorrect TItle (duplicate SLUG)");
                            ModelState.AddModelError("", "Incorrect TItle (duplicate SLUG)");
                            ViewData["BlogId"] = new SelectList(_context.Blogs, "Id", "BlogName", blogPost.BlogId);
                            return View(blogPost);
                        }

                    }

                    blogPost.Updated = DateTime.UtcNow;
                    blogPost.Created = DateTime.SpecifyKind(blogPost.Created, DateTimeKind.Utc);

                    _context.Update(blogPost);
                    await _context.SaveChangesAsync();

                    //var tagsId = _context.BlogPosts.SelectMany(t => tagsId.Tags);

                    // ------------ TAG MANAGEMENT -------------
                    // -----  STEP 1: get a tracked version of the blog post ------------
                    var currentBlogPost = await _context.BlogPosts
                                                                .Include("Tags")
                                                                .FirstOrDefaultAsync(b => b.Id == blogPost.Id);

                    currentBlogPost.Tags.Clear();
                    var tags = _context.Tags;

                    if (tagIds.Count > 0)
                    {
                        foreach (var tagId in tagIds)
                        {
                            blogPost.Tags.Add(await tags.FindAsync(tagId));
                        }
                    }

                    await _context.SaveChangesAsync();

                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogPostExists(blogPost.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

            }

            ViewData["BlogId"] = new SelectList(_context.Blogs, "Id", "BlogName", blogPost.BlogId);
            ViewData["TagIds"] = new MultiSelectList(_context.Tags, "Id", "Text", tagIds);
            return View(blogPost);
        }


        // GET: BlogPosts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {

AtlasBlog/Controllers/BlogsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AtlasBlog.Data;
using AtlasBlog.Models;
using AtlasBlog.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using AtlasBlog.Services;
using AtlasBlog.ViewModels;
using X.PagedList;

namespace AtlasBlog.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class BlogsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IImageService _imageService;
        private readonly SearchService _searchService;

        public BlogsController(ApplicationDbContext context, IImageService imageService, SearchService searchService)
        {
            _context = context;
            _imageService = imageService;
            _searchService = searchService;
        }

        // GET: Blogs
        [AllowAnonymous]
        public async Task<IActionResult> Index(int? pageNum)
        {
            pageNum ??= 1;

            var blogs = await _context.Blogs.Include(b => b.BlogPosts)
                                            .OrderByDescending(b => b.Created)
                                                .ToPagedListAsync(pageNum, 3);

            
            //var model = await _context.Blogs.Include(b => b.BlogPosts).ToListAsync();


            return View(blogs);
            //await _context.Blogs.ToListAsync()
        }

        [AllowAnonymous]
        public async Task<IActionResult> SearchIndex(int? pageNum, string searchTerm)
        {
            pageNum ??= 1;
            var pageSize = 4;

            //  ---  SEARCH SERVICE WILL BE USED FOR THIS ----------------<
            var posts = _searchService.TermSearch(searchTerm);
            var pagedPosts = await posts.ToPagedListAsync(pageNum, pageSize);

            ViewData["SearchTerm"] = searchTerm;
            return View(pagedPosts);

        }

        // GET: Blogs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                                           .FirstOrDefaultAsync(m => m.Id == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // GET: Blogs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BlogName,Description,Title,ResearchTopic,ImageData,ImageExt")] Blog blog, IFormFile imageFile)
        {
            if (ModelState.IsValid)
            {
                if (blog is not null)
                {
                    blog.ImageData= await _imageService.ConvertFileToByteArrayAsync(imageFile);
                    blog.ImageExt = imageFile.ContentType;
                }

                // ------- SPECIFY THE DATETIME KIND FOR THE INCOMING CREATED DATE ----------------------------->
                blog.Created = DateTime.UtcNow;

                _context.Add(blog);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(blog);
        }

        // GET: Blogs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var blog = await _context.Blogs.Include(b => b.BlogPosts).FindAsync(id);
            var blog = await _context.Blogs.FindAsync(id);
            if (blog == null)                                        //.FindAsync(id);

            {
                return NotFound();
            }

            return View(blog);
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BlogName,Description,Title,ResearchTopic,Created,Updated")] Blog blog)
        {
            if (id != blog.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    blog.Updated = DateTime.UtcNow;
                    blog.Created = DateTime.SpecifyKind(blog.Created, DateTimeKind.Utc);

                    //blog.ResearchTopic = await _imageService.ConvertFileToByteArrayAsync(blog);
                    //blog.ImageExt = imageFile.ContentType;

                    _context.Update(blog);
                    await _context.SaveChangesAsync();

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogExists(blog.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(blog);
        }

        // GET: Blogs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // POST: Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blog = await _context.Blogs.FindAsync(id);
            _context.Blogs.Remove(blog);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlogExists(int id)
        {
            return _context.Blogs.Any(e => e.Id == id);
        }
    }
}

AtlasBlog/Views/Home/Index.cshtml
@using AtlasBlog.Services.Interfaces
@using Microsoft.IdentityModel
@using Microsoft.AspNetCore.Identity
@using X.PagedList.Mvc.Core
@using X.PagedList.Web.Common

@inject IImageService _imageService
@inject SignInManager<BlogUser> SignInManager
@inject UserManager<BlogUser> _userManager

@model X.PagedList.IPagedList<Blog>

    
<header class="masthead container-fluid pageBG" style="">
                
@{
    ViewData["Title"] = "Home Index";
}

@if ((User.IsInRole("Moderator")) || (User.IsInRole("Administrator")))
{
    <h5 class="purpleText pt-3">Home Index</h5>
}

@if (User.IsInRole("Administrator"))
{
    <p>
        <a asp-action="Create" asp-controller="Blogs">Create New</a>
    </p>
}


<div class="py-md-5 d-flex d-block">
    <div class="container">
        <div class="row gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading text-center">
                    <h3 class="subheading">A Code Research Blog</h3>

                    <form asp-action="SearchIndex" asp-controller="BlogPosts">
                        <input name="SearchTerm" class="form-control" />
                        <button type="submit" class="btn-secondary btn-outline w-100 fw-bold redText">SEARCH</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

</header>   

<div class="row  mt-3">
    @foreach (var item in Model!.OrderByDescending(i => i.BlogName))
    {
        <div class="col-12 col-md-3">
            <div class="px-1 g-3 h-100 border glass-jw-style purpleText">
                <a class="noUnderline" asp-controller="Blogs" asp-action="Index" asp-route-slug="">
                    <div class="text-center overflow">
                        <h5 class="card-title text-center overflow " style="">@Html.DisplayFor(modelItem => item.BlogName)</h5>
                        <div class="border-top border-bottom py-2">@Html.DisplayFor(modelItem => item.ResearchTopic)</div>
                    </div>
                    <div class="row p-2">
                        <div class="text-center">
                            <span>
                                @if(item.ImageData == null)
                                {
                                    <img class="img-fluid float-start rounded-circle" style="max-width: 3rem; height: auto;"
                                 src="~/img/DefaultImage.png">Posted: @Html.DisplayFor(modelItem => item.Created);
                                }
                                <img class="img-fluid float-start rounded-circle" style="max-width: 3rem; height: auto;"
                                 src="@_imageService.ConvertByteArrayToFile(item.ImageData!, item.ImageExt!)">Posted: @Html.DisplayFor(modelItem => item.Created)
                            </span>
                        </div>
                    </div>
                </a>
                <div class="d-flex align-items-end justify-content-sm-center">
                    <div class="">
                        @if (User.IsInRole("Administrator"))
                        {
                            <a asp-action="Edit" asp-controller="Blogs" asp-route-id="@item.Id">
                                <i class="bi-pencil-fill" style="font-size: 1.5rem; color:lightyellow;"></i>
                            </a>
                            <a asp-action="Details" asp-controller="Blogs" asp-route-id="@item?.Id">
                                <i class="bi-person-fill" style="font-size: 1.5rem; color:lightyellow;"></i>
                            </a>
                            <a asp-action="Delete" asp-controller="Blogs" asp-route-id="@item?.Id">
                                <i class="bi-trash-fill" style="font-size: 1.5rem; color:red;"></i>
                            </a>
                        }
                    </div>
                </div>
            </div>
        </div>
    }
</div>


<div class="row mt-4">
    <div class="d-flex align-content-end">
        <div class="purpleText" type="text">

            Page @(Model!.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
            @Html.PagedListPager(Model, pageNum => Url.Action("Index", new { pageNum }),
            new PagedListRenderOptions
            {
            LiElementClasses = new string[] { "page-link"},
            PageClasses = new string[] { "page-link" }
            })

        </div>
    </div>
</div>